# Generated by Django 5.0.4 on 2024-04-24 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('email', models.TextField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('EmployeeId', models.TextField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('chapterId', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('chapterName', models.CharField(max_length=100)),
                ('publicationDate', models.TimeField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookId', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=100)),
                ('publicationDate', models.TimeField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('JournalId', models.TextField(primary_key=True, serialize=False)),
                ('journalName', models.CharField(max_length=100)),
                ('publicationDate', models.TimeField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.faculty')),
            ],
        ),
    ]
